-- =======================================================
-- CRIAÇÃO DA TABELA PROFESSOR
-- =======================================================

CREATE TABLE PROFESSOR (
    ID           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME         VARCHAR2(150) NOT NULL,
    DEPARTAMENTO VARCHAR2(100) NOT NULL,
    EMAIL        VARCHAR2(150) NOT NULL,
    TITULACAO    VARCHAR2(80)
);

-- Regra de unicidade de e-mail
CREATE UNIQUE INDEX UK_PROFESSOR_EMAIL ON PROFESSOR(EMAIL);

-- =======================================================
-- INSERÇÕES NA TABELA ALUNO
-- =======================================================
INSERT INTO ALUNO (NOME, CURSO) VALUES ('Mariana Costa', 'Engenharia de Software');
INSERT INTO ALUNO (NOME, CURSO) VALUES ('Lucas Oliveira', 'Ciência da Computação');
INSERT INTO ALUNO (NOME, CURSO) VALUES ('Beatriz Almeida', 'Análise e Desenvolvimento de Sistemas');
INSERT INTO ALUNO (NOME, CURSO) VALUES ('Rafael Martins', 'Sistemas de Informação');
INSERT INTO ALUNO (NOME, CURSO) VALUES ('Júlia Pereira', 'Engenharia da Computação');


-- =======================================================
-- INSERÇÕES NA TABELA PROFESSOR
-- =======================================================
INSERT INTO PROFESSOR (NOME, DEPARTAMENTO, EMAIL, TITULACAO) VALUES ('Dr. Ricardo Neves', 'Tecnologia', 'ricardo.neves@universidade.edu', 'Doutor');
INSERT INTO PROFESSOR (NOME, DEPARTAMENTO, EMAIL, TITULACAO) VALUES ('Dra. Cláudia Sampaio', 'Ciências Exatas', 'claudia.sampaio@universidade.edu', 'Doutora');
INSERT INTO PROFESSOR (NOME, DEPARTAMENTO, EMAIL, TITULACAO) VALUES ('Me. Fernando Souza', 'Tecnologia', 'fernando.souza@universidade.edu', 'Mestre');
INSERT INTO PROFESSOR (NOME, DEPARTAMENTO, EMAIL, TITULACAO) VALUES ('Dra. Lúcia Guimarães', 'Inovação Digital', 'lucia.guimaraes@universidade.edu', 'Doutora');
INSERT INTO PROFESSOR (NOME, DEPARTAMENTO, EMAIL, TITULACAO) VALUES ('Me. André Valente', 'Ciências Exatas', 'andre.valente@universidade.edu', 'Mestre');